const { gql } = require('apollo-server');

module.exports = gql`
  type Query {
    hello: String!

    urisaki2: [URISAKI2]

    gzaikozan: [GZAIKOZAN]

    tableList: [Table!]!

    describe(tablename: String!): Describe!

    tranSummary(
      tablename: String!
      buscd: String!
      ymd: String!
    ): [TranSummary!]

    tran(
      tablename: String!
      buscd: String!
      ymd: String!
      aitcd: String
      denno: String
    ): [Tran!]!

    hinsyu(
      offset: Int!
      chunk: Int!
    ): [Hinsyu!]!

    urisaki(
      buscd: String!
    ): [Aitsak!]

    kaisaki(
      buscd: String!
    ): [Aitsak!]
  }

  type Table {
    id: String!
    name: String
    title: String
    filename: String 
  }

  type Describe {
    info: DescribeInfo!
    columns: [Column!]!
  }

  type DescribeInfo {
    id: String!
    name: String!
    upper: String
    title: String 
    filename: String 
  }

  type Column {
    no: Int 
    title: String 
    prefix: String!
    name: String!
    type: String!
    size: String
    iskey: String 
    biko: String 
  }

  type TranSummary {
    AITCD: String
    DENNO: String
    KENSU: String
    KINGK: String
  }

  type Tran {
    YOHKB: String
    SZDKB: String
    SISCD: String
    BUSCD: String
    TANCD: String
    DENNO: String
    DENSQ: String
    NDPAG: String
    UDGYO: String
    AITCD: String
    SRYMD: String
    HSYMD: String
    NSYMD: String
    FRYMD: String
    MHYMD: String
    KSYMD: String
    HINCD: String
    BRNCD: String
    MAISU: String
    KINGK: String
    NKRCD: String
    NYKNO: String
    NYKKB: String
    SKRCD: String
    ZSHNO: String
    SYKKB: String
    ZSHNG: String
    TDNKB: String
    ADNKB: String
    HDNKB: String
    SHZKB: String
    KSKFG: String
    HASKB: String
    LOTNO: String
    ENTRY: String
    UNSCD: String
    HATSU: String
    CHAKU: String
    KAINO: String
    HSBUS: String
    UNCHN: String
    HJURY: String
    HENTR: String
    HMEIG: String
    HCYMD: String
    HCBIN: String
    HCHUK: String
    CUNCH: String
    HSZK6: String
    HKOSU: String
    MARFG: String
    MEGKB: String
    TDNO1: String
    TDNO2: String
    SQYMD: String
    NDENO: String
    HTANKB:String
    ARARI: String
    SKFLG: String
    HDNFG: String
    SDPFG: String
    NIPFG: String
    SIRAI: String
    SOSKB: String
    JYUNO: String
    JYUSQ: String
    EIGKB: String
    OKFLG: String
    ZAIKB: String
    SMYMD: String
    COMNT: String
    MIKKB: String
    SNDKB: String
    DNYMD: String
    KRDEN: String
    LOC01: String
    LOC02: String
    LOC03: String
    LOC04: String
    LOC05: String
    COMN1: String
    COMN2: String
    COMN3: String
    ZAMAI: String
    MOMAI: String
    MOKIN: String
    FLG01: String
    FLG02: String
    FLG03: String
    FLG04: String
    FLG05: String
    GENCD: String
    KAKCD: String
    IKUCD: String
    TAICD: String
    CHA01: String
    CHA02: String
    CHA03: String
    VAR01: String
    VAR02: String
    VAR03: String
  }

  type Hinsyu {
    HINCD: String
    HINNM: String
    SIZEN: String
    YORYO: String
    JURKB: String
    IRISU: String
    HGRC1: String
    HGRC2: String
    BIKOU: String
    TOROK: String
    MENTE: String
    MNTAN: String
    JYURY: String
    SHINM: String
    SSIZE: String
    GENFG: String
    KAKFG: String
    IKUFG: String
    TAIFG: String
    PBFLG: String
    DAICD: String
    CHUCD: String
    SBRCD: String
    USEFG: String
  }

  type Aitsak
  {
    USBKB: String
    BUSCD: String
    AITCD: String
    GRPNO: String
    MEISJ: String
    SEISJ: String
    MEISK: String
    SEISK: String
    ADRS1: String
    ADRS2: String
    ADRS3: String
    ADRS4: String
    ADRS5: String
    YUBIN: String
    TELNO: String
    KENCD: String
    YOSIN: String
    GYSCD: String
    TANCD: String
    TANCH: String
    SIMKB: String
    KSBKB: String
    KSHKB: String
    SEQKB: String
    BOBKB: String
    TORKB: String
    SQHKB: String
    ZHSKB: String
    SEIBO: String
    INDXJ: String
    INDXK: String
    TSYMD: String
    TEYMD: String
    TOROK: String
    MENTE: String
    SHACD: String
    BUMON: String
    TANHO: String
    SAGRP: String
    GYSC1: String
    TESSY: String
    TESUM: String
    TESKB: String
    TESKS: String
    TESKH: String
    TESSR: String
    TESKJ: String
    CHUKB: String
    TNLNK: String
    TNYMD: String
    TNMNT: String
    JJOKY: String
    HJOKY: String
    GKIBO: String
    GSTDY: String
    GONER: String
    GFUHY: String
    GSRAI: String
    GCMNT: String
    BIKOU: String
    GMEIS: String
    GSEIS: String
    GMEIF: String
    GSEIF: String
    ADRG1: String
    ADRG2: String
    ADRG3: String
    ADRG4: String
    ADRG5: String
    YUBNG: String
    TELNG: String
    FAXNO: String
    KENCG: String
    GYOSN: String
    GYGCD: String
    GYSMA: String
    GYSUB: String
    HINM1: String
    HINM2: String
    HINM3: String
    HINM4: String
    HINM5: String
    SGYMD: String
    SEYMD: String
    SIHON: String
    NINZU: String
    JOUJO: String
    KEIFG: String
    KYKKB: String
    HOSFG: String
    HOSNM: String
    TNPKB: String
    TORKG: String
    KEIRE: String
    BIKOG: String
    JIGSU: String
    JIGNM: String
    INDXG: String
    INDFG: String
    NAMED: String
    YOMID: String
    YAKUD: String
    ADRD1: String
    ADRD2: String
    ADRD3: String
    ADRD4: String
    ADRD5: String
    YUBND: String
    TELND: String
    KENC2: String
    SENEN: String
    GAKOD: String
    SOTSU: String
    DNYMD: String
    BIKOD: String
    GTORO: String
    GMENT: String
    GSHAC: String
    DKENC: String
    KGYCD: String
    KEIYM: String
    KEIBK: String
    HOSYM: String
    HOSNA: String
    HOSBK: String
    TNPSY: String
    TNPYM: String
    TNPBK: String
    OBEUM: String
    OBEYM: String
    KESAN: String
    TOKUM: String
    TOKYM: String
    TOKBK: String
    YOSBK: String
    GYGC1: String
    GYGS1: String
    GYGS2: String
    URLAD: String
    SINYO: String
    COMNT: String
    KBNK1: String
    KBNK2: String
    KBNK3: String
    KBNK4: String
    KBNK5: String
    KYAK1: String
    KYAK2: String
    KYAK3: String
    KYAK4: String
    KYAK5: String
    KIRE1: String
    KIRE2: String
    KIRE3: String
    KIRE4: String
    KIRE5: String
    KURI1: String
    KURI2: String
    KURI3: String
    KURI4: String
    KURI5: String
    KKAB1: String
    KKAB2: String
    KKAB3: String
    KKAB4: String
    KKAB5: String
    NBUSCD: String
    KAMEINO: String
    TORKEINO: String
    KEINO: String
    SYOCD: String
  }, 
  type URISAKI2 {
    AIT_USBKB: String
    AIT_BUSCD: String
    AIT_AITCD: String
    AIT_GRPNO: String
    AIT_MEISJ: String
    AIT_SEISJ: String
    AIT_MEISK: String
    AIT_SEISK: String
    AIT_ADRS1: String
    AIT_ADRS2: String
    AIT_ADRS3: String
    AIT_ADRS4: String
    AIT_ADRS5: String
    AIT_YUBIN: String
    AIT_TELNO: String
    AIT_KENCD: String
    AIT_YOSIN: String
    AIT_GYSCD: String
    AIT_TANCD: String
    AIT_TANCH: String
    AIT_SIMKB: String
    AIT_KSBKB: String
    AIT_KSHKB: String
    AIT_SEQKB: String
    AIT_BOBKB: String
    AIT_TORKB: String
    AIT_SQHKB: String
    AIT_ZHSKB: String
    AIT_SEIBO: String
    AIT_INDXJ: String
    AIT_INDXK: String
    AIT_TSYMD: String
    AIT_TEYMD: String
    AIT_TOROK: String
    AIT_MENTE: String
    AIT_SHACD: String
    AIT_BUMON: String
    AIT_TANHO: String
    AIT_SAGRP: String
    AIT_GYSC1: String
    AIT_TESSY: String
    AIT_TESUM: String
    AIT_TESKB: String
    AIT_TESKS: String
    AIT_TESKH: String
    AIT_TESSR: String
    AIT_TESKJ: String
    AIT_CHUKB: String
    AIT_TNLNK: String
    AIT_TNYMD: String
    AIT_TNMNT: String
    AIT_JJOKY: String
    AIT_HJOKY: String
    AIT_GKIBO: String
    AIT_GSTDY: String
    AIT_GONER: String
    AIT_GFUHY: String
    AIT_GSRAI: String
    AIT_GCMNT: String
    AIT_BIKOU: String
    AIT_GMEIS: String
    AIT_GSEIS: String
    AIT_GMEIF: String
    AIT_GSEIF: String
    AIT_ADRG1: String
    AIT_ADRG2: String
    AIT_ADRG3: String
    AIT_ADRG4: String
    AIT_ADRG5: String
    AIT_YUBNG: String
    AIT_TELNG: String
    AIT_FAXNO: String
    AIT_KENCG: String
    AIT_GYOSN: String
    AIT_GYGCD: String
    AIT_GYSMA: String
    AIT_GYSUB: String
    AIT_HINM1: String
    AIT_HINM2: String
    AIT_HINM3: String
    AIT_HINM4: String
    AIT_HINM5: String
    AIT_SGYMD: String
    AIT_SEYMD: String
    AIT_SIHON: String
    AIT_NINZU: String
    AIT_JOUJO: String
    AIT_KEIFG: String
    AIT_KYKKB: String
    AIT_HOSFG: String
    AIT_HOSNM: String
    AIT_TNPKB: String
    AIT_TORKG: String
    AIT_KEIRE: String
    AIT_BIKOG: String
    AIT_JIGSU: String
    AIT_JIGNM: String
    AIT_INDXG: String
    AIT_INDFG: String
    AIT_NAMED: String
    AIT_YOMID: String
    AIT_YAKUD: String
    AIT_ADRD1: String
    AIT_ADRD2: String
    AIT_ADRD3: String
    AIT_ADRD4: String
    AIT_ADRD5: String
    AIT_YUBND: String
    AIT_TELND: String
    AIT_KENC2: String
    AIT_SENEN: String
    AIT_GAKOD: String
    AIT_SOTSU: String
    AIT_DNYMD: String
    AIT_BIKOD: String
    AIT_GTORO: String
    AIT_GMENT: String
    AIT_GSHAC: String
    AIT_DKENC: String
    AIT_KGYCD: String
    AIT_KEIYM: String
    AIT_KEIBK: String
    AIT_HOSYM: String
    AIT_HOSNA: String
    AIT_HOSBK: String
    AIT_TNPSY: String
    AIT_TNPYM: String
    AIT_TNPBK: String
    AIT_OBEUM: String
    AIT_OBEYM: String
    AIT_KESAN: String
    AIT_TOKUM: String
    AIT_TOKYM: String
    AIT_TOKBK: String
    AIT_YOSBK: String
    AIT_GYGC1: String
    AIT_GYGS1: String
    AIT_GYGS2: String
    AIT_URLAD: String
    AIT_SINYO: String
    AIT_COMNT: String
    AIT_KBNK1: String
    AIT_KBNK2: String
    AIT_KBNK3: String
    AIT_KBNK4: String
    AIT_KBNK5: String
    AIT_KYAK1: String
    AIT_KYAK2: String
    AIT_KYAK3: String
    AIT_KYAK4: String
    AIT_KYAK5: String
    AIT_KIRE1: String
    AIT_KIRE2: String
    AIT_KIRE3: String
    AIT_KIRE4: String
    AIT_KIRE5: String
    AIT_KURI1: String
    AIT_KURI2: String
    AIT_KURI3: String
    AIT_KURI4: String
    AIT_KURI5: String
    AIT_KKAB1: String
    AIT_KKAB2: String
    AIT_KKAB3: String
    AIT_KKAB4: String
    AIT_KKAB5: String
    AIT_NBUSCD: String
    AIT_KAMEINO: String
    AIT_TORKEINO: String
    AIT_KEINO: String
    AIT_SYOCD: String
  }
  type GZAIKOZAN {
    GZA_HINCD: String
    HIZ_HINNM: String
    HIZ_SIZEN: String
    HIZ_YORYO: String
    HIZ_JURKB: String
    HIZ_IRISU: String
    GZA_HTANK: String
    GZA_ZAIKB: String
    GZA_ZSHNO: String
    GZA_NYKNO: String
    GZA_NSKKB: String
    GZA_NKYMD: String
    GZA_UPYMD: String
    GZA_MOTOK: String
    GZA_MKING: String
    GZA_GENZA: String
    GZA_JUCHU: String
    KAD_COPRM: String
    KAD_FCTRM: String
    GZA_GENCD: String
    GZA_KAKCD: String
    GZA_IKUCD: String
    GZA_TAICD: String
    GZA_KURCD: String
    TGEN_GENNM: String
    TKAK_GENNM: String
    TIKU_IKUNM: String
    TTAI_TAINM: String
  }
`;